### ISSUE TITLE
Certmanager crashes on upload of invalid key pair

### ISSUE THREAD

**Issue by pi-sigma** [maykinmedia/django-simple-certmanager#15]
The certmanager allows upload of invalid key pairs but then raises an error when trying to access the certificates in the admin. In order to regain access to the certificates, the invalid pair has to be removed manually from the database.

**Steps to reproduce:**

1. Upload a valid public certificate
2. Upload the same certificate as private key

**Expected behavior:**

The upload of invalid key pairs should be prevented.

**Comment by SilviaAmAm** [comment]
DH Taiga issue 301
