### ISSUE TITLE
Add a check to the admin list/detail page indicating a valid chain

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/django-simple-certmanager#4]
There should be a function that validates if the certificate has a valid root certificate.

This can be achieved in several ways like, having a cert with the full chain or having all intermediate certificates installed on the server. There's functions to check this (requests does it) I guess.

**Comment by CharString** [comment]
@joeribekker Can you review the code and test whether #6 solves your use case?

If the root G1 is not deployed in the system cacert.pem, the check will fail.

Possible expansions:
- add the check as a validator on the form/modelfield
- turn the raised openssl exceptions into helpful messages
  (boolean invalid/valid isn't particularly helpful with debugging an issue)

**Comment by joeribekker** [comment]
Fixed by #6
