### ISSUE TITLE
Signing request information changes do not create a new CSR

### ISSUE THREAD

**Issue by sergei-maertens** [maykinmedia/django-simple-certmanager#41]
If you make a mistake in the details, you would be tempted to edit the request in the admin and expect the CSR to be updated. This currently does not happen, because as soon as a CSR/private key pair is generated, they are never overwritten.

I see a couple of options to address this:

1. Make all fields read-only as soon as the request was saved. A new request needs to be created to make corrections (bad UX)
2. Detect if any fields changed in value, and if so, create a new CSR (optionally also just generate a new private key if that's easiest)
3. Add an explicit booleanfield/checkbox "generate a new CSR" so that they can tick this after making changes

I think option 2. is the nicest, but also a bit complicated because you need to compare before/after values and then decide if a new CSR needs to be generated. It's also hard to keep up to date if any additional fields are added in the future.

Option 3. is probably the most practical.

**Comment by sam-bertin** [comment]
I think the issue you mentioned makes sense. It is in fact annoying for the user having to create a new `SigningRequest` if he made a mistake. Letting the user decide if the CSR needs to be regenerated is a good option. 

I was worried that allowing the regeneration of the CSR would mess with the next feature (CSR/Certificate association) but I don't see a valid reason to modify the Subject Information from the CSR after a public certifacte has been associated with it. So I don't think that it will clash with the rest of the process either.  

The associated P.R => https://github.com/maykinmedia/django-simple-certmanager/pull/42/
