### ISSUE TITLE
Remove / Encrypt Private Keys in Database

### ISSUE THREAD

**Issue by sam-bertin** [maykinmedia/django-simple-certmanager#45]
The private key from the `SigningRequest` are stored in the data base without encryption for now. 
It might be a good idea to either encrypt them or remove the private key from the instance when the instance has been associated to a `Certificate`.

**Comment by alextreme** [comment]
Discussed with @CharString, this is a valid issue. As database encryption has other problems of its own I suggest that we remove the privatekey from the SigningRequest after a valid certificate has been uploaded
