### ISSUE TITLE
Change SigningRequest.csr to a property

### ISSUE THREAD

**Issue by CharString** [maykinmedia/django-simple-certmanager#47]
Instead of it being a text shown, provide a download link that serves the text in a file with the correct mime type

- [x] Change `SigningRequest.csr` to a property, that way there's no issues with keeping values in sync. We haven't released a version with the csr field, so changing the existing should be fine 
- [x] Replace the field on the SigningRequest change form with a link to the `download_csr` action. That action should be a GET request.

This should be enough:
```python
@property
def csr(self) -> CSR:
    return generate_csr(
        key_pem=self.private_key,
        common_name=self.common_name,
        organization_name=self.organization_name,
        locality=self.locality_name,
        state_or_province=self.state_or_province_name,
        country=self.country_name,
    )
```

**Comment by sergei-maertens** [comment]
Some things that will require attention:

* Downloading CSRs in bulk via the admin action (in a ZIP file) is nice, however if it's too much work to update, removing it in favour of downloading them one-by-one is fine. I don't expect people to create 10 CSRs at once and drop them with their CA.
* CSR download link, yes, but permission checks are crucial here - the download link should only be visible (and accessible) if you have change permissions on the signing request model.
